=== eduardocruzpalacios/un-xml-records-transformation-by-xslt-in-html-and-css/dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Declaración de elementos
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-->
<!ELEMENT resolucion (encabezado_primera_pagina, pie_primera_pagina, cuadro_superior, titulo, subtitulo, texto, encabezado, pie)>
<!-- El elemento raiz es "resolucion". No he incluido ningún indicador de frecuencia para expresar que cada documento que vayamos a marcar solo podrá tener un elemento denominado "resolucion". El elemento resolucion debe tener todos esos elementos una sola vez. He diferenciado el contenido del encabezado y el pie de página de las primeras páginas y el resto porque su contenido no es el mismo. El elemento "cuadro_superior" se refiere al contenido que hay entre dos líneas horizontales en la primera página e incluye un logotipo, el órgano que aprueba la resolución, y el lugar y fecha de la aprobación. Con los elementos "titulo" y "subtitulo" me refiero a los dos párrafos destacados en negrita que hay antes del texto de la resolución, propiamente dicho.-->
<!ELEMENT encabezado_primera_pagina (organizacion, identificador)>
<!ELEMENT organizacion (#PCDATA)>
<!ELEMENT identificador (#PCDATA)>
<!-- Utilizo "#PCDATA" para permitir el uso de caracteres como la "/".-->
<!ELEMENT pie_primera_pagina (codigo_barras, reciclar?, codigo_qr?)>
<!-- Partiendo del supuesto de que los elementos que contiene el elemento "pie_primera_pagina" son imágenes insertas en el documento, solo he dejado el código de barras como obligatorio porque es el único que aparece en todos los documentos.-->
<!ELEMENT codigo_barras EMPTY>
<!ELEMENT reciclar EMPTY>
<!ELEMENT codigo_qr EMPTY>
<!-- Los dejo como elementos vacíos por el supuesto anteriormente mencionado: son imágenes insertas en el documento, y no contienen otroas elementos o texto (entiendo que el texto de las imágenes del código de barras y del icono de "se ruega recliclar" es parte de la imagen y no hay que escribirlo en el documento).-->
<!ELEMENT cuadro_superior (logotipo_organizacion, organo, lugar_aprobacion, fecha_aprobacion)>
<!ELEMENT logotipo_organizacion EMPTY>
<!-- Elemento vacío porque es una imagen insertada, y no contiene texto. Es posible que el texto "Consejo de Seguridad" forme parte de la imagen. Si fuera así, habría que suprimir el siguiente elemento, "organo".-->
<!ELEMENT organo (#PCDATA)>
<!ELEMENT lugar_aprobacion (#PCDATA)>
<!ELEMENT fecha_aprobacion (#PCDATA)>
<!-- Estos tres elementos únicamente contienen texto. He incluido #PCDATA por si en un futuro se decidieran escribir con caracteres especiales, como las barras o guiones ("/" o "-") en la fecha. Además, Distrito general está abreviado, así que necesita incluir un punto (".").-->
<!ELEMENT titulo (#PCDATA | negrita)*>
<!ELEMENT subtitulo (#PCDATA | negrita)*>
<!-- Elementos con modelo de contenido mixto. Incluyen texto y el resaltado del mismo en negrita.-->
<!ELEMENT negrita (#PCDATA)>
<!ELEMENT texto (parrafo+)>
<!ELEMENT parrafo (#PCDATA | cursiva | documento_relacionado | palabra_clave | organizacion_relacionada | lugar | persona_relacionada | proyecto_relacionado)*>
<!-- El elemento párrafo es obligatorio, repetible y además tiene un modelo de contenido mixto para poder incluir texto en cursiva y otros elementos hijos, que relacionen el contenido del documento con otros documentos. Todos los elementos hijos son de solo texto.-->
<!ELEMENT cursiva (#PCDATA)>
<!ELEMENT documento_relacionado (#PCDATA)>
<!ELEMENT palabra_clave (#PCDATA)>
<!ELEMENT organizacion_relacionada (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT persona_relacionada (#PCDATA)>
<!ELEMENT proyecto_relacionado (#PCDATA)>
<!ELEMENT encabezado (identificador)>
<!-- El elmento "identificador" ya se definió anteriormente, por lo que ya no es necesario volver a hacerlo.-->
<!ELEMENT pie (identificador_codigo_barras)>
<!ELEMENT identificador_codigo_barras (#PCDATA)>
<!-- He denominado a este elemento "identificador_codigo_barras" porque el número que aparece en el pie de página de los documentos coincide y de hecho, se refiere a él, con el número que hay encima del código de barras.-->
<!-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Declaración de atributos
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-->
<!ATTLIST resolucion
	id CDATA #REQUIRED
	organizacion NMTOKENS #REQUIRED
	ente_aprobacion NMTOKENS #REQUIRED
	lugar_aprobacion NMTOKENS #REQUIRED
	fecha_aprobacion_iso8601 NMTOKENS #REQUIRED
	sesion_aprobacion NMTOKENS #REQUIRED
	pais_referencia_iso3166 NMTOKENS #REQUIRED
	idioma_iso639 NMTOKENS "es"
>
<!-- Todos estos atributos están contemplados para la búsqueda y recuperación de documentos. Por ello, son todos obligatorios, con la excepción del idioma, que tiene un valor por defecto.-->
<!ATTLIST codigo_barras
	fuente CDATA #REQUIRED
	texto CDATA #IMPLIED
>
<!ATTLIST reciclar
	fuente CDATA #REQUIRED
	texto CDATA #IMPLIED
>
<!ATTLIST codigo_qr
	fuente CDATA #REQUIRED
	url CDATA #REQUIRED
>
<!ATTLIST logotipo_organizacion
	fuente CDATA #REQUIRED
>
<!-- Todos los atrributos "fuente" son obligatorios porque es imprescindible que se incorpore la referencia desde la cual se insertará la imagen correspondiente en el documento.-->
<!ATTLIST documento_relacionado
	nombre CDATA #REQUIRED
	id ID #IMPLIED
>
<!-- El atributo "id" del documento relacionado es optativo porque no dispongo de los valores correspondientes a los documentos relacionados que aparecen en los documentos que se deben marcar en la practica 2. Si tuviera dichos valores, lo pondría obligatorio, que es cómo ayudaría a la búsqueda y recuperación de documentos.-->
<!ATTLIST organizacion_relacionada
	nombre NMTOKENS #REQUIRED
>
<!ATTLIST lugar
	pais_iso3166 NMTOKENS #REQUIRED
>
<!ATTLIST persona_relacionada
	nombre NMTOKENS #REQUIRED
>
<!ATTLIST proyecto_relacionado
	nombre NMTOKENS #REQUIRED
>
<!ATTLIST identificador_codigo_barras
	numero CDATA #REQUIRED
>
<!-- Este número será el número completo que hay encima del código de barras-->

=== eduardocruzpalacios/un-xml-records-transformation-by-xslt-in-html-and-css/documento1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by usuario (empresa) -->
<!DOCTYPE resolucion SYSTEM "dtd.dtd">
<?xml-stylesheet type="text/xsl" href="transformacion.xslt"?>
<resolucion id="S/RES/2015 (2011)" organizacion="Naciones Unidas" ente_aprobacion="Consejo de Seguridad" lugar_aprobacion="Distrito general" fecha_aprobacion_iso8601="2011-10-24" sesion_aprobacion="6635" pais_referencia_iso3166="so">
	<encabezado_primera_pagina>
		<organizacion>Naciones Unidas</organizacion>
		<identificador>S/RES/2015 (2011)</identificador>
	</encabezado_primera_pagina>
	<pie_primera_pagina>
		<codigo_barras fuente="codigo_barras.jpg" texto="[Código de barras]"/>
		<reciclar fuente="reciclar.jpg" texto="Se ruega reciclar"/>
		<codigo_qr fuente="" url="http://www.un.org/es/comun/docs/?symbol=s/res/2015%20(2011)"/>
	</pie_primera_pagina>
	<cuadro_superior>
		<logotipo_organizacion fuente="nu.jpg"/>
		<organo>Consejo de Seguridad</organo>
		<lugar_aprobacion>Distr. general</lugar_aprobacion>
		<fecha_aprobacion>24 de octubre de 2011</fecha_aprobacion>
	</cuadro_superior>
	<titulo>
		<negrita>Resolución 2015 (2011)</negrita>
	</titulo>
	<subtitulo>
		<negrita>Aprobada por el Consejo de Seguridad en su 6635ª sesión, celebrada el 24 de octubre de 2011</negrita>
	</subtitulo>
	<texto>
		<parrafo>
			<cursiva>El Consejo de Seguridad</cursiva>,</parrafo>
		<parrafo>
			<cursiva>Recordando</cursiva> sus resoluciones anteriores relativas a la situación en Somalia, en particular las <documento_relacionado nombre="resolucion 1918 (2010)">resoluciones 1918 (2010)</documento_relacionado> y <documento_relacionado nombre="resolucion 1976 (2011">1976 (2011)</documento_relacionado>,</parrafo>
		<parrafo>
			<cursiva>Gravemente preocupado todavía</cursiva> por la creciente amenaza que los actos de <palabra_clave>piratería</palabra_clave> y <palabra_clave>robo a mano armada</palabra_clave> en el mar cometidos contra buques frente a las costas de Somalia representan para la situación en <lugar pais_iso3166="so">Somalia</lugar>, los Estados de la región y otros Estados, así como para la <palabra_clave>navegación internacional</palabra_clave>, la <palabra_clave>seguridad</palabra_clave> de las <palabra_clave>rutas marítimas</palabra_clave> comerciales y la seguridad de los navegantes y otras personas, y gravemente preocupado también por el mayor grado de violencia que emplean los piratas y las personas implicadas en los actos de robo a mano armada en el mar frente a las costas de Somalia,</parrafo>
		<parrafo>
			<cursiva>Poniendo de relieve</cursiva> la importancia de hallar una solución general al problema de la piratería y el robo a mano armada en el mar frente a las costas de Somalia,</parrafo>
		<parrafo>
			<cursiva>Destacando</cursiva> la necesidad de aumentar las posibilidades que Somalia tiene de lograr un crecimiento económico sostenible como medio para combatir las causas subyacentes de la piratería, incluida la <palabra_clave>pobreza</palabra_clave>, contribuyendo así a la erradicación duradera de la piratería y el robo a mano armada en el mar frente a las costas de Somalia y de las actividades ilícitas conexas,</parrafo>
		<parrafo>
			<cursiva>Reafirmando</cursiva> su respeto por la soberanía, la integridad territorial, la independencia política y la unidad de Somalia,</parrafo>
		<parrafo>
			<cursiva>Reafirmando</cursiva> que el derecho internacional, reflejado en la <documento_relacionado nombre="Convencion de las Naciones Unidas sobre el Derecho del Mar de 10 de diciembre de 1982">Convención de las Naciones Unidas sobre el Derecho del Mar de 10 de diciembre de 1982 (“la Convención”)</documento_relacionado>, en particular sus artículos 100, 101 y 105, establece el marco jurídico aplicable a la lucha contra la piratería y el robo a mano armada en el mar, así como a otras actividades realizadas en los océanos,</parrafo>
		<parrafo>
			<cursiva>Reafirmando además</cursiva> que las disposiciones de la presente resolución solo son aplicables a la situación imperante en Somalia y no afectan a los derechos y obligaciones o responsabilidades de los Estados Miembros en virtud del derecho internacional,</parrafo>
		<parrafo>
			<cursiva>Teniendo presente</cursiva> el <documento_relacionado nombre="Codigo de Conducta de Dbjibouti">Código de Conducta de Djibouti</documento_relacionado> relativo a la represión de la piratería y el robo a mano armada contra buques en el Océano Índico occidental y el Golfo de Adén y <cursiva>reconociendo</cursiva> el compromiso de los Estados signatarios de examinar su legislación nacional a fin de asegurar que las leyes nacionales tipifiquen como delito la piratería y el robo a mano armada contra buques y establecer directrices adecuadas para ejercer su jurisdicción, realizar investigaciones y enjuiciar a los presuntos delincuentes,</parrafo>
		<parrafo>
			<cursiva>Encomiando</cursiva> a los Estados que han enmendado su legislación interna para tipificar como delito la piratería y facilitar el enjuiciamiento de los presuntos piratas en sus tribunales nacionales, respetando las disposiciones aplicables del derecho internacional, incluidas las normas de derechos humanos, y <cursiva>destacando</cursiva> la necesidad de que los Estados prosigan sus esfuerzos en tal sentido,</parrafo>
		<parrafo>
			<cursiva>Observando con preocupación al mismo tiempo</cursiva> que la legislación nacional de algunos Estados no contiene disposiciones que tipifiquen como delito la piratería o disposiciones procesales para enjuiciar efectivamente a los presuntos piratas,</parrafo>
		<parrafo>
			<cursiva>Reafirmando la importancia</cursiva> del enjuiciamiento nacional de los presuntos piratas para luchar contra la piratería frente a las costas de Somalia,</parrafo>
		<parrafo>
			<cursiva>Condenando enérgicamente</cursiva> la práctica continuada de toma de <palabra_clave>rehenes</palabra_clave> por los presuntos <palabra_clave>piratas</palabra_clave> que operan frente a las costas de Somalia, <cursiva>expresando grave preocupación</cursiva> por las condiciones inhumanas que padecen los rehenes en <palabra_clave>cautividad</palabra_clave>, <cursiva>reconociendo</cursiva> el impacto negativo en sus familias, <cursiva>pidiendo</cursiva> la liberación inmediata de todos los rehenes y <cursiva>haciendo notar</cursiva> la importancia de que los Estados Miembros cooperen respecto de la cuestión de la toma de rehenes y la necesidad de que se enjuicie a los presuntos piratas por tomar rehenes,</parrafo>
		<parrafo>
			<cursiva>Reconociendo</cursiva> que, pese a los esfuerzos realizados hasta la fecha por los Estados para enjuiciar a los presuntos piratas a nivel nacional, la labor en curso a este respecto sigue siendo insuficiente y se debe hacer más para asegurar que los presuntos piratas sean efectivamente llevados ante la justicia,</parrafo>
		<parrafo>
			<cursiva>Reiterando su preocupación</cursiva> por el hecho de que un gran número de personas sospechosas de piratería tengan que ser puestas en libertad sin comparecer ante la justicia, <cursiva>reafirmando</cursiva> que el hecho de no enjuiciar a las personas responsables de actos de piratería y robo a mano armada en el mar frente a las costas de Somalia menoscaba las actividades de lucha contra la piratería de la comunidad internacional y <cursiva>decidido</cursiva> a crear las condiciones necesarias para asegurar que los piratas rindan cuentas de sus actos,</parrafo>
		<parrafo>
			<cursiva>Observando con interés</cursiva> la conclusión que figura en el informe del <persona_relacionada nombre="Secretario General">Secretario General</persona_relacionada> sobre las modalidades para el establecimiento de tribunales especializados contra la piratería en Somalia <documento_relacionado nombre="Informe del Secretario General sobre las modalidades para el establecimiento de tribunales especializados contra la pirateria en Somalia">(S/2011/360)</documento_relacionado> de que, si se proporciona suficiente asistencia internacional, los juicios contra la piratería que se están realizando en tribunales ubicados en Somalilandia y Puntlandia pueden llegar a cumplir las normas internacionales dentro de unos tres años, y <cursiva>expresando su esperanza</cursiva>, en consonancia con el informe mencionado del Secretario General, de que se acelere ese calendario si se localizan y contratan expertos adecuados, incluso procedentes de la diáspora somalí,</parrafo>
		<parrafo>
			<cursiva>Acogiendo con beneplácito</cursiva> las consultas entre las Naciones Unidas y Estados de la región, entre ellos <organizacion_relacionada nombre="Seychelles">Seychelles</organizacion_relacionada>, <organizacion_relacionada nombre="Mauricio">Mauricio</organizacion_relacionada> y la <organizacion_relacionada nombre="Republica Unida de Tanzania">República Unida de Tanzanía</organizacion_relacionada>, y la disposición expresada por la República Unida de Tanzanía de prestar asistencia a la comunidad internacional, en las condiciones adecuadas, para enjuiciar a los sospechosos de cometer actos de piratería en su territorio,</parrafo>
		<parrafo>
			<cursiva>Determinando</cursiva> que los incidentes de piratería y robo a mano armada en el mar frente a las costas de Somalia agravan la situación imperante en Somalia, que sigue constituyendo una amenaza para la paz y la seguridad internacionales en la región,</parrafo>
